In [2]:
import numpy as np
arr = np.random.randint(1,12, size=10)
print("Original Array:", arr)

Original Array: [ 1  9  5  2 11  2  7 10  8 10]


In [3]:
arr1 = np.random.rand(1,12)
print("Original Array 2D:", arr1)

Original Array 2D: [[0.89337131 0.59288743 0.81693099 0.20766277 0.76381761 0.42654867
  0.8249365  0.66661188 0.36674275 0.04581759 0.22917663 0.64347543]]


In [4]:
arr2 = np.random.randn(1,12)
print("Original Array 3D:", arr2)

Original Array 3D: [[-1.61185962  0.87240733 -1.12326416 -1.30031599  0.8183943   0.19574376
   0.9051651  -1.61587871  1.13764002  0.78983965 -0.10610488  2.06060202]]


In [5]:
arr3 = np.random.random_integers(1,12)
print("Original Array 4D:", arr3)

Original Array 4D: 11


/tmp/ipykernel_19995/972520359.py:1: DeprecationWarning: This function is deprecated. Please call randint(1, 12 + 1) instead
  arr3 = np.random.random_integers(1,12)


In [6]:
arr3 = np.arange(1,12)
print(arr3)

[ 1  2  3  4  5  6  7  8  9 10 11]


In [2]:
import numpy as np

# Create a 1D array
arr1 = np.array([1, 2, 3, 4, 5])

# Create a 2D array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])

# Create a 3D array
arr3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr1, arr2, arr3)

[1 2 3 4 5] [[1 2 3]
 [4 5 6]] [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
