In [5]:
import numpy as np
arr1D = np.array([1,2,3,4,5,6])
print(arr1D.shape)

(6,)


In [13]:
arr2_1D = np.array ([1,2,3,4,5,6,7,8,9,10,11,12])
arr2_2D = arr2_1D.reshape(4,3)
print(arr2_2D, "\n")
print(arr2_2D.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] 

(4, 3)


In [19]:
ha = np.random.randint(1,50)
for i in range(1,6):
    print(ha + i)

12
13
14
15
16


In [26]:
arr = np.arange(1,22)
np.random.shuffle(arr)

print(arr.reshape(7,3))

[[19 15  8]
 [14  2 18]
 [ 3  9 10]
 [13  1  5]
 [ 4 17 21]
 [20 12  6]
 [11 16  7]]


In [29]:
ar = np.random.rand(4,3)
print(ar)

[[0.54792923 0.34077108 0.40311164]
 [0.05648236 0.85814422 0.23188303]
 [0.21678265 0.04804428 0.6489507 ]
 [0.08435367 0.69673313 0.67949687]]


In [9]:

lst = ["Janzeb", "Shahzaib", "Nadir Ali", "Kamran", "Sanaullah"]
print(lst[-5])

Janzeb


In [11]:
print("\"Nadir Ali\"")

"Nadir Ali"
