<h1> Assignment1: Random and Numpy </h1> 
 <h5 > Date: 10/10/2024 </br> Submitted by: Nadir Ali Khan </h5>

<h3>Task 1: Generating  Random Arrays</h3>

In [2]:
import numpy as np


In [ ]:
# Task 1.1: Create a 1D array of 5 random integers between 1 and 50 using
# numpy.random.randint.
arr1D = np.random.randint(1, 51, size = 5)
print(arr1D)

In [ ]:
#  Task 1.2: Generate a 2x2 matrix of random floats between 0 and 1 using
# numpy.random.rand.
matrix = np.random.rand(2,2)
print(matrix)


In [ ]:
# Task 1.3: Create a 3x3 identity matrix using numpy.eye.
eye = np.eye(3,3)
print(eye)

<h3>Task 2: Basic Array Manipulation</h3>

In [ ]:
# Task 2.1: Create a 1D array of 10 random numbers between 0 and 10. Sort
# the array in ascending order.
arr_1d = np.random.randint(0,11, size=10)
print(np.sort(arr_1d))

In [16]:
# Task 2.2: Generate a 4x4 matrix of random integers between 1 and 20.
# Replace all values greater than 10 with 0.

arr_1 = np.random.randint(1,21, size = (4,4))
print(arr_1, "\n")
arr_1[arr_1 > 10] = 0
print(arr_1)


[[10 20  9  1]
 [ 1 12 13  5]
 [20 11  2  4]
 [20 16  1  8]] 

[[10  0  9  1]
 [ 1  0  0  5]
 [ 0  0  2  4]
 [ 0  0  1  8]]


In [ ]:
# Task 2.3: Create a 1D array of 10 numbers and replace the maximum value
# with -1.

arrID = np.random.randint(1,20, size=10 )
mx = max(arrID)
print(f"{mx} is replaced by -1 ")
print(arrID)
arrID[arrID == max(arrID) ] = -1
print(arrID)

<h3>Task3: Simple Statistical Analysis</h3>

In [ ]:
# Task 3.1: Create an array of 20 random integers between 1 and 100. Find
# the minimum, maximum, and mean values.
arr1 = np.random.randint(1,100, size=20)
length = len(arr1)
add = sum(arr1)
mean = add / length
print(np.sort(arr1))
print(f'The minimum value is {min(arr1)}')
print(f'The maximum value is {max(arr1)}')
print(f'The mean value is {mean}')


In [17]:
# Task 3.2:
arr2 = np.random.rand(1,30)
for x in arr2 > 0.5:
    count = sum(x)
    print(f'Total numbers > 0.5 is/are {count}')
    
print("\n", arr2, )
    

Total numbers > 0.5 is/are 20

 [[0.82556086 0.42274211 0.41822855 0.21135854 0.25702181 0.6801703
  0.97763604 0.26946376 0.71613914 0.54217846 0.38311203 0.82659282
  0.51086652 0.83809329 0.97647779 0.68693085 0.55096675 0.83747961
  0.49933893 0.19415162 0.69856864 0.51080619 0.13189808 0.77814845
  0.69601272 0.89780731 0.97562741 0.47887761 0.65040149 0.99937584]]


<h3>Task 4: Random Selections</h3>

In [ ]:
# Task 4.1: 1D array with no replacemenet
size = 5
arr3 = np.random.choice(range(1,21), size, replace=False)
print(arr3)

In [ ]:

# Task 4.2 10 Random number with shuffling
arr4 = np.random.randint(0, 9, size=10)
print(arr4)
np.random.shuffle(arr4)
print(arr4)

<h3>Task5: Basic Probability Experiments</h3>

In [ ]:
# Task 5.1: Simulate flipping a coin 10 times. Use numpy.random.choice to
# randomly choose between "Heads" and "Tails".

coin = np.random.choice(["Heads","Tails"], size=10)
print(coin)

   


In [ ]:
# Task 5.2: Roll a 6-sided die 20 times. Count how many times the number 5
# appears.
die = np.random.choice([1,2,3,4,5,6], size=20)
c5 = np.sum(die == 5)
print(f'The number 5 appears {c5} times')
print(die)


In [18]:
# Task 5.3: Create a 1D array with 100 random integers between 1 and 10.
# Count the number of instances for each unique value.

arr5 = np.random.randint(1, 10, size=100)
print("This is the Orignal Array \n",arr5, "\n")

printed = set()
for x in arr5:
    if x not in printed:
        print(f'{x} : {np.sum(x==arr5)} Instances')
        printed.add(x)
        


This is the Orignal Array 
 [2 1 3 1 8 9 7 5 6 8 4 5 4 5 7 5 7 3 4 2 3 5 6 4 2 2 7 6 6 9 2 3 7 7 1 2 1
 2 2 8 7 5 1 9 8 3 9 2 6 1 6 4 9 8 4 1 1 2 7 5 2 7 6 4 4 1 5 4 8 2 2 1 4 1
 8 1 2 3 8 6 5 7 8 9 2 5 7 9 3 5 3 1 6 2 1 3 2 2 5 2] 

2 : 19 Instances
1 : 14 Instances
3 : 9 Instances
8 : 9 Instances
9 : 7 Instances
7 : 11 Instances
5 : 12 Instances
6 : 9 Instances
4 : 10 Instances
